#ifndef __YOG_GC_BDW_H__
#define __YOG_GC_BDW_H__

#include <stddef.h>
#include "yog/vm.h"
#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/gc/bdw.c */
void* YogBDW_alloc(YogEnv*, YogVm*, ChildrenKeeper, Finalizer, size_t);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
