#if !defined(__YOG_GC_BDW_H__)
#define __YOG_GC_BDW_H__

#include <stddef.h>
#include "yog/yog.h"

struct YogBDW {
};

typedef struct YogBDW YogBDW;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/gc/bdw.c */
void* YogBDW_alloc(YogEnv*, YogBDW*, ChildrenKeeper, Finalizer, size_t);
void YogBDW_init(YogEnv*, YogBDW*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
