#ifndef __YOG_GC_GENERATIONAL_H__
#define __YOG_GC_GENERATIONAL_H__

#include <stddef.h>

/* TODO: commonize with yog/yog.h */
#ifndef __YOG_YOG_H__
typedef int BOOL;
#define FALSE   0
#define TRUE    (!(FALSE))
typedef struct YogEnv YogEnv;
typedef void* (*ObjectKeeper)(YogEnv*, void*);
typedef void (*ChildrenKeeper)(YogEnv*, void*, ObjectKeeper);
typedef void (*Finalizer)(YogEnv*, void*);
#endif

struct YogGenerational {
};

typedef struct YogGenerational YogGenerational;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/gc/generational.c */
void YogGenerational_finalize(YogEnv*, YogGenerational*);
void YogGenerational_initialize(YogEnv*, YogGenerational*, BOOL, size_t, size_t, size_t, void*, ObjectKeeper);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
