#if !defined(__YOG_GC_GENERATIONAL_H__)
#define __YOG_GC_GENERATIONAL_H__

#include <stddef.h>
#include "yog/gc/copying.h"
#include "yog/gc/mark-sweep-compact.h"

/* TODO: commonize with yog/yog.h */
#if !defined(__YOG_YOG_H__) && !defined(__YOG_GC_GENERATIONAL_H__)
typedef int BOOL;
#define FALSE   0
#define TRUE    (!(FALSE))
typedef struct YogEnv YogEnv;
typedef void* (*ObjectKeeper)(YogEnv*, void*);
typedef void (*ChildrenKeeper)(YogEnv*, void*, ObjectKeeper);
typedef void (*Finalizer)(YogEnv*, void*);
#endif

#define ERR_GEN_NONE        0
#define ERR_GEN_MMAP        1
#define ERR_GEN_MUNMAP      2
#define ERR_GEN_MALLOC      3
#define ERR_GEN_UNKNOWN     4

struct YogGenerational {
    struct YogGenerational* prev;
    struct YogGenerational* next;
    BOOL refered;

    unsigned int err;
    struct YogCopying copying;
    struct YogMarkSweepCompact msc;
    unsigned int tenure;
    BOOL has_young_ref;
};

typedef struct YogGenerational YogGenerational;

#define PTR2GEN(p)      (*((unsigned int*)(p) - 1))
#define IS_YOUNG(p)     (PTR2GEN(p) == GEN_YOUNG)

#define GEN_YOUNG   1
#define GEN_OLD     2

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/gc/generational.c */
YOG_EXPORT void* YogGenerational_alloc(YogEnv*, YogGenerational*, ChildrenKeeper, Finalizer, size_t);
YOG_EXPORT void YogGenerational_alloc_heap(YogEnv*, YogGenerational*);
YOG_EXPORT void* YogGenerational_copy_young_object(YogEnv*, void*, ObjectKeeper, void*);
YOG_EXPORT void YogGenerational_finalize(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_init(YogEnv*, YogGenerational*, size_t, size_t, size_t, uint_t);
YOG_EXPORT BOOL YogGenerational_is_empty(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_major_cheney_scan(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_major_delete_garbage(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_major_keep_vm(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_major_post_gc(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_minor_cheney_scan(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_minor_delete_garbage(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_minor_keep_vm(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_minor_post_gc(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_oldify_all(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_prepare(YogEnv*, YogGenerational*);
YOG_EXPORT void YogGenerational_trace_grey(YogEnv*, YogGenerational*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
