#if !defined(__YOG_MARK_SWEEP_H__)
#define __YOG_MARK_SWEEP_H__

#include <stddef.h>
#include "yog/yog.h"

struct YogMarkSweep {
    struct YogMarkSweep* prev;
    struct YogMarkSweep* next;
    BOOL refered;

    struct YogMarkSweepHeader* header;
    size_t threshold;
    size_t allocated_size;
    void* root;
    ChildrenKeeper root_keeper;
};

typedef struct YogMarkSweep YogMarkSweep;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/gc/mark-sweep.c */
void* YogMarkSweep_alloc(YogEnv*, YogMarkSweep*, ChildrenKeeper, Finalizer, size_t);
void YogMarkSweep_delete_garbage(YogEnv*, YogMarkSweep*);
void YogMarkSweep_finalize(YogEnv*, YogMarkSweep*);
void YogMarkSweep_init(YogEnv*, YogMarkSweep*, size_t);
BOOL YogMarkSweep_is_empty(YogEnv*, YogMarkSweep*);
void YogMarkSweep_keep_vm(YogEnv*, YogMarkSweep*);
void YogMarkSweep_post_gc(YogEnv*, YogMarkSweep*);
void YogMarkSweep_prepare(YogEnv*, YogMarkSweep*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
