#if !defined(__YOG_GC_MARK_SWEEP_COMPACT_H__)
#define __YOG_GC_MARK_SWEEP_COMPACT_H__

#include <stddef.h>
#include "yog/gc.h"
#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/gc/mark-sweep-compact.c */
YOG_EXPORT void* YogMarkSweepCompact_alloc(YogEnv*, YogHeap*, ChildrenKeeper, Finalizer, size_t);
YOG_EXPORT void YogMarkSweepCompact_delete(YogEnv*, YogHeap*);
YOG_EXPORT void YogMarkSweepCompact_delete_garbage(YogEnv*, YogHeap*);
YOG_EXPORT ChildrenKeeper YogMarkSweepCompact_get_children_keeper(YogEnv*, YogHeap*, void*);
YOG_EXPORT BOOL YogMarkSweepCompact_is_empty(YogEnv*, YogHeap*);
YOG_EXPORT void YogMarkSweepCompact_keep_root(YogEnv*, void*, ChildrenKeeper, YogHeap*);
YOG_EXPORT void* YogMarkSweepCompact_mark(YogEnv*, void*, ObjectKeeper, void*);
YOG_EXPORT void YogMarkSweepCompact_mark_in_breadth_first(YogEnv*, YogHeap*);
YOG_EXPORT void* YogMarkSweepCompact_mark_recursively(YogEnv*, void*, ObjectKeeper, void*);
YOG_EXPORT YogHeap* YogMarkSweepCompact_new(YogEnv*, size_t);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
