
DIR = ..\..\..\pthreads-w32

all:
	cd $(DIR)
	$(MAKE) /$(MAKEFLAGS) /NOLOGO VC-static-debug

clean:
	cd $(DIR)
	$(MAKE) /$(MAKEFLAGS) /NOLOGO clean

# vim: tabstop=8 shiftwidth=8 noexpandtab
