#!/bin/sh

if [ "${#}" != 0 ]; then
  args="${@}"
else
  args="tests"
fi

exec py.test-2.7 --showlocals --verbose -r fEsXx ${args}

# py.test in OpenBSD and FreeBSD exits at non zero when any tests fails. This
# spec disturbs plural tests.
exit 0

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
