#!/bin/sh

run()
{
  "$@"
  if [ "$?" != 0 ]; then
    echo "Failed: $@"
    exit 1
  fi
}

cleanup()
{
  run rm -rf "${tmp_dir}/${archive}"
}

do_test()
{
  (cd "${tmp_dir}/${archive}" && run mkdir $$ && run ./configure --prefix=`pwd`/$$ CFLAGS=-I${HOME}/include LDFLAGS=-L${HOME}/lib && run make && run make install)
}

archive="${1}"
if [ -z "${archive}" ]; then
  echo "Usage: ${0} <head>"
  exit 1
fi

untar="tar xf -"
tmp_dir="/tmp/$$"
run mkdir -p "${tmp_dir}"

cleanup
dir=`pwd`
(cd "${tmp_dir}" && run zcat "${dir}/${archive}.tar.gz" | ${untar})
do_test

cleanup
(cd "${tmp_dir}" && run bzcat "${dir}/${archive}.tar.bz2" | ${untar})
do_test

which xzcat >/dev/null
if [ $? = 0 ]; then
  cleanup
  (cd "${tmp_dir}" && run xzcat "${dir}/${archive}.tar.xz" | ${untar})
  do_test
fi

cleanup
(cd "${tmp_dir}" && run unzip -q "${dir}/${archive}.zip")
do_test

run rm -rf "${tmp_dir}"

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
