#!/bin/sh

cleanup()
{
  rm -rf "${archive}"
  if [ $? != 0 ]; then
    echo "can't cleanup"
    exit 2
  fi
}

do_test()
{
  (cd "${archive}" && mkdir $$ && ./configure --prefix=`pwd`/$$ CFLAGS=-I${HOME}/include LDFLAGS=-L${HOME}/lib && make && make install)
  if [ $? != 0 ]; then
    echo "can't make"
    exit 2
  fi
}

archive="${1}"
if [ -z "${archive}" ]; then
  echo "Usage: ${0} <head>"
  exit 1
fi

untar="tar xf -"

cleanup
zcat "${archive}.tar.gz" | ${untar}
if [ $? != 0 ]; then
  echo "can't extract ${archive}.tar.gz"
  exit 2
fi
do_test

cleanup
bzcat "${archive}.tar.bz2" | ${untar}
if [ $? != 0 ]; then
  echo "can't extract ${archive}.tar.bz2"
  exit 2
fi
do_test

which xzcat >/dev/null
if [ $? = 0 ]; then
  cleanup
  xzcat "${archive}.tar.xz" | ${untar}
  if [ $? != 0 ]; then
    echo "can't extract ${archive}.tar.xz"
    exit 2
  fi
  do_test
fi

cleanup
unzip -q "${archive}.zip"
if [ $? != 0 ]; then
  echo "can't extract ${archive}.zip"
  exit 2
fi
do_test

cleanup

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
