Document: yog
Title: Debian yog Manual
Author: <insert document author here>
Abstract: This manual describes what yog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yog/yog.sgml.gz

Format: postscript
Files: /usr/share/doc/yog/yog.ps.gz

Format: text
Files: /usr/share/doc/yog/yog.text.gz

Format: HTML
Index: /usr/share/doc/yog/html/index.html
Files: /usr/share/doc/yog/html/*.html

  
