#!/bin/sh

s="
"
matched=`"${CORGI}" match "[ \\\\t\\\\n\\\\r]" "${s}" | hd  | head -1 | awk '{ print $2 }'`
if [ "${matched}" != "0a" ]; then
  exit 1
fi
exit 0

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
