--- !ditz.rubyforge.org,2008-03-06/project 
name: Yog
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: document
- !ditz.rubyforge.org,2008-03-06/component 
  name: misc
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.1
  status: :released
  release_time: 2009-09-10 08:25:58.934469 Z
  log_events: 
  - - 2009-09-02 18:01:23.079877 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2009-09-10 08:25:58.934495 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.2
  status: :released
  release_time: 2009-10-10 03:13:55.768858 Z
  log_events: 
  - - 2009-09-10 11:22:55.991304 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2009-10-10 03:13:55.768894 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.3
  status: :released
  release_time: 2009-10-26 01:02:01.493630 Z
  log_events: 
  - - 2009-10-20 05:34:06.406606 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2009-10-26 01:02:01.493655 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.4
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-11-07 17:52:44.836037 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - |-
      Objectives:
      1. Improve GC
      2. Performance tuning
