--- !ditz.rubyforge.org,2008-03-06/project 
name: Yog
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: doc
- !ditz.rubyforge.org,2008-03-06/component 
  name: misc
- !ditz.rubyforge.org,2008-03-06/component 
  name: lib
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.1
  status: :released
  release_time: 2009-09-10 08:25:58.934469 Z
  log_events: 
  - - 2009-09-02 18:01:23.079877 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2009-09-10 08:25:58.934495 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.2
  status: :released
  release_time: 2009-10-10 03:13:55.768858 Z
  log_events: 
  - - 2009-09-10 11:22:55.991304 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2009-10-10 03:13:55.768894 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.3
  status: :released
  release_time: 2009-10-26 01:02:01.493630 Z
  log_events: 
  - - 2009-10-20 05:34:06.406606 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2009-10-26 01:02:01.493655 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.4
  status: :released
  release_time: 2010-03-04 13:05:59.324888 Z
  log_events: 
  - - 2009-11-07 17:52:44.836037 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - |-
      Objectives:
      1. Improve GC
      2. Performance tuning
  - - 2010-03-04 13:05:59.324925 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.5
  status: :released
  release_time: 2010-04-24 18:30:10.015490 Z
  log_events: 
  - - 2010-04-18 15:23:40.220757 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2010-04-24 18:30:10.015560 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.6
  status: :released
  release_time: 2010-06-11 04:10:54.885604 Z
  log_events: 
  - - 2010-05-26 15:54:29.798721 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - ""
  - - 2010-06-11 04:10:54.885633 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.11
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-07-14 19:19:04.245153 Z
    - Sumi Tomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - "An objective of this version is quality for casual using."
