
ONIG_DIR = ..\..\..\onig

all:
	cd $(ONIG_DIR)
	$(MAKE) /$(MAKEFLAGS) /NOLOGO /Fwin32\Makefile

clean:
	cd $(ONIG_DIR)
	$(MAKE) /$(MAKEFLAGS) /NOLOGO /Fwin32\Makefile clean

# vim: tabstop=8 shiftwidth=8 noexpandtab
