#if !defined(__YOG_ARG_H__)
#define __YOG_ARG_H__

#include <stdint.h>
#include "yog/yog.h"

struct YogArgInfo {
    unsigned int argc;
    YogVal argnames;
    YogVal arg_index;

    unsigned int blockargc;
    ID blockargname;
    uint8_t blockarg_index;

    unsigned int varargc;
    uint8_t vararg_index;

    unsigned int kwargc;
    uint8_t kwarg_index;
};

typedef struct YogArgInfo YogArgInfo;

#define ARG_INFO(v)     PTR_AS(YogArgInfo, (v))

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/arg.c */
YogVal YogArgInfo_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
