#if !defined(__YOG_ARG_H__)
#define __YOG_ARG_H__

#include "yog/yog.h"

struct YogArgInfo {
    uint_t argc;
    YogVal argnames;
    YogVal arg_index;

    uint_t blockargc;
    ID blockargname;

    uint_t varargc;

    uint_t kwargc;
};

typedef struct YogArgInfo YogArgInfo;

#define ARG_INFO(v)     PTR_AS(YogArgInfo, (v))

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
#if defined(__cplusplus)
extern "C" {
#endif
/* src/arg.c */
YogVal YogArgInfo_new(YogEnv*);


#if defined(__cplusplus)
}
#endif
/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
