#ifndef __YOG_ARRAY_H__
#define __YOG_ARRAY_H__

#include "yog/yog.h"

struct YogValArray {
    unsigned int size;
    struct YogVal items[0];
};

typedef struct YogValArray YogValArray;

struct YogArray {
    YOGBASICOBJ_HEAD;
    unsigned int size;
    struct YogValArray* body; 
};

typedef struct YogArray YogArray;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/array.c */
YogVal YogArray_at(YogEnv*, YogArray*, unsigned int);
void YogArray_extend(YogEnv*, YogArray*, YogArray*);
YogArray* YogArray_new(YogEnv*);
void YogArray_push(YogEnv*, YogArray*, YogVal);
unsigned int YogArray_size(YogEnv*, YogArray*);
YogVal YogValArray_at(YogEnv*, YogValArray*, unsigned int);
YogValArray* YogValArray_new(YogEnv*, unsigned int);
unsigned int YogValArray_size(YogEnv*, YogValArray*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
