#ifndef __YOG_ARRAY_H__
#define __YOG_ARRAY_H__

#include "yog/yog.h"

struct YogValArray {
    unsigned int size;
    struct YogVal items[0];
};

typedef struct YogValArray YogValArray;

struct YogArray {
    YOGBASICOBJ_HEAD;
    unsigned int size;
    struct YogVal body; 
};

typedef struct YogArray YogArray;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/array.c */
YogVal YogArray_at(YogEnv*, YogVal, unsigned int);
void YogArray_extend(YogEnv*, YogVal, YogVal);
YogVal YogArray_new(YogEnv*);
void YogArray_push(YogEnv*, YogVal, YogVal);
unsigned int YogArray_size(YogEnv*, YogVal);
YogVal YogValArray_at(YogEnv*, YogVal, unsigned int);
YogVal YogValArray_new(YogEnv*, unsigned int);
unsigned int YogValArray_size(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
