#if !defined(__YOG_BLOCK_H__)
#define __YOG_BLOCK_H__

#include "yog/object.h"
#include "yog/table.h"
#include "yog/yog.h"

struct YogBasicBlock {
    YOGBASICOBJ_HEAD;
    YogVal code;
};

#define BASIC_BLOCK(obj)  ((YogBasicBlock*)obj)

typedef struct YogBasicBlock YogBasicBlock;

struct YogBlock {
    struct YogBasicBlock base;
    YogVal locals;
    YogVal outer_vars;
    YogVal globals;
};

#define TYPE_BLOCK  ((type_t)YogBlock_new)

#define BLOCK(obj)  ((YogBlock*)(obj))

typedef struct YogBlock YogBlock;

struct YogPackageBlock {
    struct YogBasicBlock base;
    YogVal self;
    YogVal vars;
};

#define TYPE_PACKAGE_BLOCK  ((type_t)YogPackageBlock_new)

#define PACKAGE_BLOCK(obj)  ((YogPackageBlock*)obj)

typedef struct YogPackageBlock YogPackageBlock;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
#if defined(__cplusplus)
extern "C" {
#endif
/* src/block.c */
YogVal YogBlock_new(YogEnv*);
YogVal YogPackageBlock_define_class(YogEnv*, YogVal);
YogVal YogPackageBlock_new(YogEnv*);


#if defined(__cplusplus)
}
#endif
/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
