#ifndef __YOG_BLOCK_H__
#define __YOG_BLOCK_H__

#include "yog/yog.h"

struct YogBlock {
    YOGBASICOBJ_HEAD;
    struct YogCode* code;
};

#define BLOCK(obj)  ((YogBlock*)obj)

typedef struct YogBlock YogBlock;

struct YogPackageBlock {
    struct YogBlock base;
    struct YogVal self;
    struct YogTable* vars;
};

#define PACKAGE_BLOCK(obj)  ((YogPackageBlock*)obj)

typedef struct YogPackageBlock YogPackageBlock;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/block.c */
YogKlass* YogPackageBlock_klass_new(YogEnv*);
YogPackageBlock* YogPackageBlock_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
