#if !defined(YOG_BUILTINS_H_INCLUDED)
#define YOG_BUILTINS_H_INCLUDED

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/builtins.c */
YOG_EXPORT void YogBuiltins_boot(YogEnv*, YogVal, const char*, uint_t, char**);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
