#if !defined(__YOG_BUILTINS_H__)
#define __YOG_BUILTINS_H__

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/builtins.c */
YOG_EXPORT void YogBuiltins_boot(YogEnv*, YogVal, uint_t, char**);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
