#if !defined(__YOG_CLASSMETHOD_H__)
#define __YOG_CLASSMETHOD_H__

#include "yog/object.h"
#include "yog/yog.h"

struct YogClassMethod {
    struct YogBasicObj base;
    YogVal f;
};

typedef struct YogClassMethod YogClassMethod;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
#if defined(__cplusplus)
extern "C" {
#endif
/* src/classmethod.c */
YogVal YogClassMethod_define_class(YogEnv*);
YogVal YogClassMethod_new(YogEnv*);


#if defined(__cplusplus)
}
#endif
/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
