#if !defined(YOG_CLASSMETHOD_H_INCLUDED)
#define YOG_CLASSMETHOD_H_INCLUDED

#include "yog/object.h"
#include "yog/yog.h"

struct YogClassMethod {
    struct YogBasicObj base;
    YogVal f;
};

typedef struct YogClassMethod YogClassMethod;

#define TYPE_CLASS_METHOD TO_TYPE(YogClassMethod_new)

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/classmethod.c */
void YogClassMethod_define_classes(YogEnv*, YogVal);
YogVal YogClassMethod_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
