#if !defined(__YOG_CLASSMETHOD_H__)
#define __YOG_CLASSMETHOD_H__

#include "yog/object.h"
#include "yog/yog.h"

struct YogClassMethod {
    struct YogBasicObj base;
    YogVal f;
};

typedef struct YogClassMethod YogClassMethod;

#define TYPE_CLASS_METHOD   ((type_t)YogClassMethod_new)

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/classmethod.c */
YOG_EXPORT void YogClassMethod_define_classes(YogEnv*, YogVal);
YOG_EXPORT YogVal YogClassMethod_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
