#if !defined(__YOG_CODE_H__)
#define __YOG_CODE_H__

#include "yog/arg.h"
#include "yog/object.h"
#include "yog/thread.h"
#include "yog/yog.h"

struct YogExceptionTableEntry {
    pc_t from;
    pc_t to;
    pc_t target;
    YogJmpStatus status;
};

typedef struct YogExceptionTableEntry YogExceptionTableEntry;

struct YogExceptionTable {
    struct YogExceptionTableEntry items[0];
};

typedef struct YogExceptionTable YogExceptionTable;

struct YogLinenoTableEntry {
    pc_t pc_from;
    pc_t pc_to;
    uint_t lineno;
};

typedef struct YogLinenoTableEntry YogLinenoTableEntry;

struct YogCode {
    struct YogBasicObj base;

    YogVal arg_info;

    uint_t stack_size;
    uint_t local_vars_count;
    ID* local_vars_names;
    YogVal consts;
    YogVal insts;
    uint_t outer_size;

    uint_t exc_tbl_size;
    YogVal exc_tbl;

    uint_t lineno_tbl_size;
    YogVal lineno_tbl;

    YogVal filename;
    ID class_name;
    ID func_name;
};

typedef struct YogCode YogCode;

#define CODE(v)     PTR_AS(YogCode, (v))

#include "yog/opcodes.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/code.c */
YogVal YogCode_define_class(YogEnv*);
void YogCode_dump(YogEnv*, YogVal);
YogVal YogCode_new(YogEnv*);

/* src/code.inc */
const char* YogCode_get_op_name(OpCode);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
