#if !defined(__YOG_COMPARABLE_H__)
#define __YOG_COMPARABLE_H__

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/comparable.c */
YOG_EXPORT void YogComparable_define_classes(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
