#if !defined(__YOG_COMPILE_H__)
#define __YOG_COMPILE_H__

#include "yog/array.h"
#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/compile.c */
YOG_EXPORT YogVal YogCompiler_compile_finish_code(YogEnv*);
YOG_EXPORT YogVal YogCompiler_compile_interactive(YogEnv*, YogVal);
YOG_EXPORT YogVal YogCompiler_compile_package(YogEnv*, const char*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
