#if !defined(__YOG_COMPILE_H__)
#define __YOG_COMPILE_H__

#include "yog/array.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/compile.c */
YogVal YogCompiler_compile_module(YogEnv*, const char*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
