#if !defined(YOG_COROUTINE_H_INCLUDED)
#define YOG_COROUTINE_H_INCLUDED

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/coroutine.c */
YOG_EXPORT void YogCoroutine_define_classes(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
