#if !defined(__YOG_DICT_H__)
#define __YOG_DICT_H__

#include "yog/object.h"
#include "yog/yog.h"

struct YogDict {
    struct YogBasicObj base;
    YogVal tbl;
};

typedef struct YogDict YogDict;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/dict.c */
YogVal YogDict_klass_new(YogEnv*);
YogVal YogDict_new(YogEnv*);
void YogDict_set(YogEnv*, YogVal, YogVal, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */

