#if !defined(YOG_ENCODING_H_INCLUDED)
#define YOG_ENCODING_H_INCLUDED

#include "oniguruma.h"
#include "yog/object.h"
#include "yog/yog.h"

struct YogEncoding {
    struct YogBasicObj base;
    OnigEncoding onig_enc;
};

typedef struct YogEncoding YogEncoding;

#define TYPE_ENCODING TO_TYPE(YogEncoding_new)

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/encoding.c */
YOG_EXPORT void YogEncoding_define_classes(YogEnv*, YogVal);
YOG_EXPORT YogVal YogEncoding_get_ascii(YogEnv*);
YOG_EXPORT YogVal YogEncoding_get_default(YogEnv*);
YOG_EXPORT YogVal YogEncoding_get_utf8(YogEnv*);
YOG_EXPORT char* YogEncoding_left_adjust_char_head(YogEnv*, YogVal, const char*, const char*);
YOG_EXPORT int_t YogEncoding_mbc_size(YogEnv*, YogVal, const char*);
YOG_EXPORT YogVal YogEncoding_new(YogEnv*, OnigEncoding);
YOG_EXPORT YogVal YogEncoding_normalize_name(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
