#if !defined(__YOG_ENCODING_H__)
#define __YOG_ENCODING_H__

#include "oniguruma.h"
#include "yog/yog.h"

struct YogEncoding {
    OnigEncoding onig_enc;
};

typedef struct YogEncoding YogEncoding;

#include "yog/string.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/encoding.c */
YogVal YogEncoding_get_default(YogEnv*);
char* YogEncoding_left_adjust_char_head(YogEnv*, YogVal, const char*, const char*);
int YogEncoding_mbc_size(YogEnv*, YogVal, const char*);
YogEncoding* YogEncoding_new(YogEnv*, OnigEncoding);
YogVal YogEncoding_normalize_name(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
