#if !defined(YOG_ENV_H_INCLUDED)
#define YOG_ENV_H_INCLUDED

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/env.c */
YOG_EXPORT void YogEnv_define_classes(YogEnv*, YogHandle*);
YOG_EXPORT YogVal YogEnv_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
