#if !defined(YOG_EXCEPTION_H_INCLUDED)
#define YOG_EXCEPTION_H_INCLUDED

#include "yog/object.h"
#include "yog/yog.h"

struct YogStackTraceEntry {
    YogVal lower;
    uint_t lineno;
    YogVal filename;
    ID class_name;
    ID func_name;
};

typedef struct YogStackTraceEntry YogStackTraceEntry;

struct YogException {
    YOGBASICOBJ_HEAD;
    YogVal stack_trace;
    YogVal message;
};

typedef struct YogException YogException;

#define TYPE_EXCEPTION TO_TYPE(YogException_define_classes)

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/exception.c */
void YogException_define_classes(YogEnv*, YogVal);
YogVal YogException_get_stacktrace(YogEnv*, YogVal);

/* src/stacktrace.c */
YogVal YogStackTraceEntry_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
