#ifndef __YOG_EXCEPTION_H__
#define __YOG_EXCEPTION_H__

#include "yog/yog.h"

struct YogStackTraceEntry {
    struct YogStackTraceEntry* lower;
    unsigned int lineno;
    const char* filename;
    ID klass_name;
    ID func_name;
};

typedef struct YogStackTraceEntry YogStackTraceEntry;

struct YogException {
    YOGBASICOBJ_HEAD;
    struct YogStackTraceEntry* stack_trace;
    struct YogVal message;
};

typedef struct YogException YogException;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/exception.c */
YogException* YogBugException_new(YogEnv*);
YogKlass* YogException_klass_new(YogEnv*);

/* src/stacktrace.c */
YogStackTraceEntry* YogStackTraceEntry_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
