#if !defined(YOG_FFI_H_INCLUDED)
#define YOG_FFI_H_INCLUDED

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/ffi.c */
YOG_EXPORT void YogFFI_define_classes(YogEnv*, YogVal);
YOG_EXPORT YogVal YogFFI_load_lib(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
