#if !defined(__YOG_FIXNUM_H__)
#define __YOG_FIXNUM_H__

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/fixnum.c */
YOG_EXPORT YogVal YogFixnum_add_bignum(YogEnv*, YogVal, YogVal);
YOG_EXPORT void YogFixnum_define_classes(YogEnv*, YogVal);
YOG_EXPORT YogVal YogFixnum_multiply(YogEnv*, YogVal, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
