#if !defined(__YOG_FLOAT_H__)
#define __YOG_FLOAT_H__

#include "yog/object.h"

struct YogFloat {
    YOGBASICOBJ_HEAD;
    double val;
};

typedef struct YogFloat YogFloat;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/float.c */
YogVal YogFloat_klass_new(YogEnv*);
YogVal YogFloat_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
