#if !defined(__YOG_FRAME_H__)
#define __YOG_FRAME_H__

#include "yog/yog.h"

enum YogFrameType {
    FRAME_C,
    FRAME_METHOD,
    FRAME_NAME,
    FRAME_FINISH,
};

typedef enum YogFrameType YogFrameType;

struct YogFrame {
    YogVal prev;
    enum YogFrameType type;
};

typedef struct YogFrame YogFrame;

struct YogCFrame {
    struct YogFrame base;
    YogVal self;
    YogVal args;
    YogVal f;
#if 0
    struct YogVal locals;
    uint_t locals_size;
#endif
};

typedef struct YogCFrame YogCFrame;

struct YogOuterVars {
    uint_t size;
    YogVal items[0];
};

typedef struct YogOuterVars YogOuterVars;

struct YogScriptFrame {
    struct YogFrame base;
    pc_t pc;
    YogVal code;
    uint_t stack_size;
    YogVal stack;
    YogVal globals;
    YogVal outer_vars;
};

typedef struct YogScriptFrame YogScriptFrame;

struct YogFinishFrame {
    struct YogFrame base;
    pc_t pc;
    YogVal code;
    uint_t stack_size;
    YogVal stack;
};

typedef struct YogFinishFrame YogFinishFrame;

#define SCRIPT_FRAME(v)     PTR_AS(YogScriptFrame, (v))

struct YogNameFrame {
    struct YogScriptFrame base;
    YogVal self;
    YogVal vars;
};

typedef struct YogNameFrame YogNameFrame;

#define NAME_FRAME(v)   PTR_AS(YogNameFrame, (v))
#define NAME_VARS(v)    (NAME_FRAME(v)->vars)

#define YogKlassFrame       YogNameFrame

struct YogMethodFrame {
    struct YogScriptFrame base;
    YogVal vars;
};

typedef struct YogMethodFrame YogMethodFrame;

#define METHOD_FRAME(v)     PTR_AS(YogMethodFrame, (v))
#define LOCAL_VARS(f)       (METHOD_FRAME(f)->vars)

#define YogKlassFrame_new       YogNameFrame_new

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/frame.c */
YogVal YogCFrame_new(YogEnv*);
YogVal YogFinishFrame_new(YogEnv*);
YogVal YogMethodFrame_new(YogEnv*);
YogVal YogNameFrame_new(YogEnv*);
YogVal YogOuterVars_new(YogEnv*, uint_t);
YogVal YogScriptFrame_pop_stack(YogEnv*, YogScriptFrame*);
void YogScriptFrame_push_stack(YogEnv*, YogScriptFrame*, YogVal);

/* PROTOTYPE_END */

#define FRAME_PUSH(env, val)    do { \
    YogVal cur_frame = PTR_AS(YogThread, (env)->thread)->cur_frame; \
    YogScriptFrame_push_stack((env), PTR_AS(YogScriptFrame, cur_frame), (val)); \
} while (0)

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
