#if !defined(__YOG_FRAME_H__)
#define __YOG_FRAME_H__

#include "yog/yog.h"

enum YogFrameType {
    FRAME_C, 
    FRAME_METHOD, 
    FRAME_NAME, 
};

typedef enum YogFrameType YogFrameType;

struct YogFrame {
    YogVal prev;
    enum YogFrameType type;
};

typedef struct YogFrame YogFrame;

struct YogCFrame {
    struct YogFrame base;
    YogVal self;
    YogVal args;
    YogVal f;
#if 0
    struct YogVal locals;
    unsigned int locals_size;
#endif
};

typedef struct YogCFrame YogCFrame;

struct YogOuterVars {
    unsigned int size;
    YogVal items[0];
};

typedef struct YogOuterVars YogOuterVars;

struct YogScriptFrame {
    struct YogFrame base;
    pc_t pc;
    YogVal code;
    unsigned int stack_size;
    YogVal stack;
    YogVal globals;
    YogVal outer_vars;
};

typedef struct YogScriptFrame YogScriptFrame;

#define SCRIPT_FRAME(v)     PTR_AS(YogScriptFrame, (v))

struct YogNameFrame {
    struct YogScriptFrame base;
    YogVal self;
    YogVal vars;
};

typedef struct YogNameFrame YogNameFrame;

#define NAME_FRAME(v)   PTR_AS(YogNameFrame, (v))
#define NAME_VARS(v)    (NAME_FRAME(v)->vars)

#define YogKlassFrame       YogNameFrame
#define YogPackageFrame     YogNameFrame

struct YogMethodFrame {
    struct YogScriptFrame base;
    YogVal vars;
};

typedef struct YogMethodFrame YogMethodFrame;

#define METHOD_FRAME(v)     PTR_AS(YogMethodFrame, (v))
#define LOCAL_VARS(f)       (METHOD_FRAME(f)->vars)

#define YogKlassFrame_new       YogNameFrame_new
#define YogPackageFrame_new     YogNameFrame_new

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/frame.c */
YogVal YogCFrame_new(YogEnv*);
void YogFrame_add_locals(YogEnv*, YogCFrame*, unsigned int, ...);
YogVal YogMethodFrame_new(YogEnv*);
YogVal YogNameFrame_new(YogEnv*);
YogVal YogOuterVars_new(YogEnv*, unsigned int);
YogVal YogScriptFrame_pop_stack(YogEnv*, YogScriptFrame*);
void YogScriptFrame_push_stack(YogEnv*, YogScriptFrame*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
