#if !defined(__YOG_FUNCTION_H__)
#define __YOG_FUNCTION_H__

#include "config.h"
#if defined(HAVE_STDINT_H)
#   include <stdint.h>
#endif
#include "yog/object.h"
#include "yog/yog.h"

struct YogNativeFunction {
    struct YogBasicObj base;

    ID func_name;
    ID class_name;
    void* f;
};

typedef struct YogNativeFunction YogNativeFunction;

struct YogFunction {
    struct YogBasicObj base;

    YogVal code;
    YogVal globals;
    YogVal outer_vars;
    YogVal frame_to_long_return;
    YogVal frame_to_long_break;
};

typedef struct YogFunction YogFunction;

struct YogInstanceMethod {
    struct YogBasicObj base;

    YogVal self;
    YogVal f;
};

typedef struct YogInstanceMethod YogInstanceMethod;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/function.c */
YogVal YogCallable_call(YogEnv*, YogVal, uint_t, YogVal*);
YogVal YogCallable_call1(YogEnv*, YogVal, YogVal);
YogVal YogCallable_call2(YogEnv*, YogVal, uint_t, YogVal*, YogVal);
YogVal YogFunction_define_class(YogEnv*);
YogVal YogFunction_new(YogEnv*);
YogVal YogInstanceMethod_define_class(YogEnv*);
YogVal YogInstanceMethod_new(YogEnv*);
YogVal YogNativeFunction_define_class(YogEnv*);
YogVal YogNativeFunction_new(YogEnv*, ID, const char*, void*);
YogVal YogNativeInstanceMethod_define_class(YogEnv*);
YogVal YogNativeInstanceMethod_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
