#ifndef __YOG_FUNCTION_H__
#define __YOG_FUNCTION_H__

#include "yog/arg.h"
#include "yog/yog.h"

struct YogBuiltinFunction {
    struct YogArgInfo arg_info;
    int required_argc;

    struct YogVal (*f)();

    ID klass_name;
    ID func_name;
};

typedef struct YogBuiltinFunction YogBuiltinFunction;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/function.c */
YogBuiltinFunction* YogBuiltinFunction_new(YogEnv*, void*, ID, ID, unsigned int, unsigned int, unsigned int, int, va_list);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
