#if !defined(__YOG_GC_H__)
#define __YOG_GC_H__

#define ALLOC_OBJ_SIZE(env, val, keep_children, finalizer, size) \
    YogGC_allocate(env, &val, keep_children, finalizer, size)
#define ALLOC_OBJ(env, val, keep_children, finalizer, type) \
    ALLOC_OBJ_SIZE(env, val, keep_children, finalizer, sizeof(type))
#define ALLOC_OBJ_ITEM(env, val, keep_children, finalizer, type, size, item_type) \
    ALLOC_OBJ_SIZE(env, val, keep_children, finalizer, sizeof(type) + size * sizeof(item_type))

#if defined(GC_COPYING)
#   define GC_TYPE  YogCopying
#elif defined(GC_MARK_SWEEP)
#   define GC_TYPE  YogMarkSweep
#elif defined(GC_MARK_SWEEP_COMPACT)
#   define GC_TYPE  YogMarkSweepCompact
#elif defined(GC_GENERATIONAL)
#   define GC_TYPE  YogGenerational
#elif defined(GC_BDW)
#   define GC_TYPE  YogBDW
#endif

#include <sys/types.h>
#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/gc.c */
void YogGC_allocate(YogEnv*, YogVal*, ChildrenKeeper, Finalizer, size_t);
void YogGC_initialize(YogEnv*);
void YogGC_keep(YogEnv*, YogVal*, ObjectKeeper, void*);
void YogGC_perform(YogEnv*);
void YogGC_perform_major(YogEnv*);
void YogGC_perform_minor(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
