#if !defined(__YOG_GET_ARG_H__)
#define __YOG_GET_ARG_H__

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/get_args.c */
YOG_EXPORT void YogGetArgs_parse_args(YogEnv*, const char*, YogCArg*, YogVal, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
