#if !defined(__YOG_HANDLE_H__)
#define __YOG_HANDLE_H__

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/handle.c */
YOG_EXPORT void YogHandleScope_close(YogEnv*);
YOG_EXPORT YogHandleScope* YogHandleScope_open(YogEnv*);
YOG_EXPORT YogHandle* YogHandle_register(YogEnv*, YogVal);
YOG_EXPORT void YogHandle_sync_scope_with_env(YogEnv*);
YOG_EXPORT void YogHandles_finalize(YogHandles*);
YOG_EXPORT void YogHandles_init(YogHandles*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
