/**
 * This file was generated by "tools/inst.py src/insts.def" automatically.
 * DO NOT TOUCH!!
 */
#ifndef __YOG_INSTS_H__
#define __YOG_INSTS_H__
#if defined(__cplusplus)
extern "C" {
#endif

#define INST(name)  INST_##name

enum Inst {
    INST(PUSH_CONST) = 1, 
    INST(CALL_METHOD) = 2, 
    INST(STORE_PACKAGE) = 3, 

};

typedef enum Inst Inst;

#if defined(__cplusplus)
}
#endif
#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=c
 */
