#ifndef __YOG_METHOD_H__
#define __YOG_METHOD_H__

#include "yog/yog.h"

struct YogBuiltinBoundMethod {
    YOGBASICOBJ_HEAD;
    struct YogVal self;
    struct YogVal f;
};

typedef struct YogBuiltinBoundMethod YogBuiltinBoundMethod;

struct YogBuiltinUnboundMethod {
    YOGBASICOBJ_HEAD;
    struct YogVal f;
};

typedef struct YogBuiltinUnboundMethod YogBuiltinUnboundMethod;

struct YogScriptMethod {
    YOGBASICOBJ_HEAD;
    struct YogVal code;
    struct YogTable* globals;
    struct YogOuterVars* outer_vars;
};

typedef struct YogScriptMethod YogScriptMethod;

#define SCRIPT_METHOD(v)    OBJ_AS(YogScriptMethod, (v))

struct YogBoundMethod {
    struct YogScriptMethod base;
    struct YogVal self;
};

typedef struct YogBoundMethod YogBoundMethod;

struct YogUnboundMethod {
    struct YogScriptMethod base;
};

typedef struct YogUnboundMethod YogUnboundMethod;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/method.c */
YogVal YogBoundMethod_klass_new(YogEnv*);
YogVal YogBoundMethod_new(YogEnv*);
YogVal YogBuiltinBoundMethod_klass_new(YogEnv*);
YogVal YogBuiltinBoundMethod_new(YogEnv*);
YogVal YogBuiltinUnboundMethod_klass_new(YogEnv*);
YogVal YogBuiltinUnboundMethod_new(YogEnv*);
YogVal YogUnboundMethod_klass_new(YogEnv*);
YogVal YogUnboundMethod_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
