#if !defined(__YOG_METHOD_H__)
#define __YOG_METHOD_H__

#include "yog/object.h"
#include "yog/yog.h"

struct YogBuiltinBoundMethod {
    YOGBASICOBJ_HEAD;
    YogVal self;
    YogVal f;
};

typedef struct YogBuiltinBoundMethod YogBuiltinBoundMethod;

struct YogBuiltinUnboundMethod {
    YOGBASICOBJ_HEAD;
    YogVal f;
};

typedef struct YogBuiltinUnboundMethod YogBuiltinUnboundMethod;

struct YogScriptMethod {
    YOGBASICOBJ_HEAD;
    YogVal code;
    YogVal globals;
    YogVal outer_vars;
};

typedef struct YogScriptMethod YogScriptMethod;

struct YogBoundMethod {
    struct YogScriptMethod base;
    YogVal self;
};

typedef struct YogBoundMethod YogBoundMethod;

struct YogUnboundMethod {
    struct YogScriptMethod base;
};

typedef struct YogUnboundMethod YogUnboundMethod;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/method.c */
YogVal YogBoundMethod_klass_new(YogEnv*);
YogVal YogBoundMethod_new(YogEnv*);
YogVal YogBuiltinBoundMethod_klass_new(YogEnv*);
YogVal YogBuiltinBoundMethod_new(YogEnv*);
YogVal YogBuiltinUnboundMethod_klass_new(YogEnv*);
YogVal YogBuiltinUnboundMethod_new(YogEnv*);
YogVal YogUnboundMethod_klass_new(YogEnv*);
YogVal YogUnboundMethod_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
