#if !defined(YOG_MODULE_H_INCLUDED)
#define YOG_MODULE_H_INCLUDED

#include "yog/object.h"
#include "yog/yog.h"

struct YogModule {
    struct YogObj base;
    ID name;
};

typedef struct YogModule YogModule;

DECL_AS_TYPE(YogModule_new);
#define TYPE_MODULE TO_TYPE(YogModule_new)

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/module.c */
YOG_EXPORT void YogModule_define_classes(YogEnv*, YogVal);
YOG_EXPORT void YogModule_define_function(YogEnv*, YogVal, YogVal, const char*, YogAPI);
YOG_EXPORT YogVal YogModule_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
