#if !defined(__YOG_OBJECT_H__)
#define __YOG_OBJECT_H__

#include "yog/yog.h"

typedef uint_t type_t;

struct YogBasicObj {
    type_t type;
    uint_t id_upper;
    uint_t id_lower;
    flags_t flags;
    YogVal klass;
};

#define TYPE_BASIC_OBJ  ((type_t)YogBasicObj_init)

#define HAS_ATTRS       (1 << 0)
#define IMPORTING_PKG   (1 << 1)

#define YOGBASICOBJ_HEAD    struct YogBasicObj base
#define BASIC_OBJ(v)        PTR_AS(YogBasicObj, (v))
#define BASIC_OBJ_TYPE(v)   BASIC_OBJ(v)->type

typedef struct YogBasicObj YogBasicObj;

struct YogObj {
    YOGBASICOBJ_HEAD;
    YogVal attrs;
};

#define TYPE_OBJ    ((type_t)YogObj_new)

#define YOGOBJ_HEAD struct YogObj base
#define YOGOBJ(obj) ((struct YogObj*)obj)

typedef struct YogObj YogObj;

typedef YogVal (*Allocator)(struct YogEnv*, YogVal);

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
#if defined(__cplusplus)
extern "C" {
#endif
/* src/object.c */
void YogBasicObj_init(YogEnv*, YogVal, uint_t, uint_t, YogVal);
void YogBasicObj_keep_children(YogEnv*, void*, ObjectKeeper, void*);
YogVal YogObj_allocate(YogEnv*, YogVal);
void YogObj_class_init(YogEnv*, YogVal);
YogVal YogObj_get_attr(YogEnv*, YogVal, ID);
void YogObj_init(YogEnv*, YogVal, uint_t, uint_t, YogVal);
void YogObj_keep_children(YogEnv*, void*, ObjectKeeper, void*);
YogVal YogObj_new(YogEnv*, YogVal);
void YogObj_set_attr(YogEnv*, YogVal, const char*, YogVal);
void YogObj_set_attr_id(YogEnv*, YogVal, ID, YogVal);
void YogObject_boot(YogEnv*, YogVal);
void YogObject_eval_builtin_script(YogEnv*, YogVal);


#if defined(__cplusplus)
}
#endif
/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
