/**
 * This file was generated by "../tools/inst.py insts.def .." automatically.
 * DO NOT TOUCH!!
 */
#if !defined(__YOG_INSTS_H__)
#define __YOG_INSTS_H__
#if defined(__cplusplus)
extern "C" {
#endif

#define OP(name)  OP_##name

enum OpCode {
    OP(LOAD_SPECIAL) = 0,
    OP(POP) = 1,
    OP(PUSH_CONST) = 2,
    OP(MAKE_STRING) = 3,
    OP(STORE_NAME) = 4,
    OP(STORE_LOCAL) = 5,
    OP(MAKE_FUNCTION) = 6,
    OP(CALL_FUNCTION) = 7,
    OP(LOAD_GLOBAL) = 8,
    OP(LOAD_NAME) = 9,
    OP(LOAD_LOCAL) = 10,
    OP(JUMP) = 11,
    OP(JUMP_IF_TRUE) = 12,
    OP(JUMP_IF_FALSE) = 13,
    OP(DUP) = 14,
    OP(MAKE_MODULE) = 15,
    OP(MAKE_KLASS) = 16,
    OP(PUSH_SELF_NAME) = 17,
    OP(RET) = 18,
    OP(STORE_NONLOCAL) = 19,
    OP(LOAD_NONLOCAL) = 20,
    OP(STORE_GLOBAL) = 21,
    OP(LOAD_ATTR) = 22,
    OP(MAKE_ARRAY) = 23,
    OP(MAKE_DICT) = 24,
    OP(FINISH) = 25,
    OP(PRINT_TOP) = 26,
    OP(STORE_ATTR) = 27,
    OP(NOT) = 28,

};

typedef enum OpCode OpCode;

#if defined(__cplusplus)
}
#endif
#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=c
 */
