#include "yog/config.h"
#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/path.c */
YOG_EXPORT void YogPath_define_classes(YogEnv*, YogHandle*);
YOG_EXPORT YogVal YogPath_dirname(YogEnv*, YogHandle*);
YOG_EXPORT void YogPath_eval_builtin_script(YogEnv*, YogVal);
YOG_EXPORT YogVal YogPath_from_string(YogEnv*, const char*);
YOG_EXPORT YogVal YogPath_getcwd(YogEnv*);
YOG_EXPORT YogHandle* YogPath_join(YogEnv*, YogHandle*, const char*);
YOG_EXPORT YogHandle* YogPath_join2(YogEnv*, YogHandle*, YogHandle*);

/* PROTOTYPE_END */

/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
