#include "yog/config.h"
#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/path.c */
YogVal YogPath_abs(YogEnv*, YogHandle*);
void YogPath_define_classes(YogEnv*, YogHandle*);
YogVal YogPath_dirname(YogEnv*, YogHandle*);
void YogPath_eval_builtin_script(YogEnv*, YogVal);
YogVal YogPath_from_string(YogEnv*, const char*);
YogVal YogPath_getcwd(YogEnv*);
YogHandle* YogPath_join(YogEnv*, YogHandle*, const char*);
YogHandle* YogPath_join2(YogEnv*, YogHandle*, YogHandle*);

/* PROTOTYPE_END */

/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
