#if !defined(YOG_POPEN_H_INCLUDED)
#define YOG_POPEN_H_INCLUDED

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/process.c */
void YogProcess_define_classes(YogEnv*, YogHandle*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
