#if !defined(__YOG_POPEN_H__)
#define __YOG_POPEN_H__

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/process.c */
YOG_EXPORT void YogProcess_define_classes(YogEnv*, YogHandle*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
