#if !defined(YOG_PROPERTY_H_INCLUDED)
#define YOG_PROPERTY_H_INCLUDED

#include "yog/object.h"
#include "yog/yog.h"

struct YogProperty {
    struct YogBasicObj base;

    YogVal getter;
    YogVal setter;
};

typedef struct YogProperty YogProperty;

DECL_AS_TYPE(YogProperty_new);
#define TYPE_PROPERTY TO_TYPE(YogProperty_new)

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/property.c */
void YogProperty_define_classes(YogEnv*, YogVal);
YogVal YogProperty_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
