#ifndef __YOG_REGEXP_H__
#define __YOG_REGEXP_H__

#include "oniguruma.h"
#include "yog/yog.h"

struct YogRegexp {
    YOGBASICOBJ_HEAD;
    OnigRegex onig_regexp;
};

typedef struct YogRegexp YogRegexp;

struct YogMatch {
    YOGBASICOBJ_HEAD;
    struct YogString* str;
    struct YogRegexp* regexp;
    OnigRegion* onig_region;
};

typedef struct YogMatch YogMatch;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/regexp.c */
YogKlass* YogMatch_klass_new(YogEnv*);
YogMatch* YogMatch_new(YogEnv*, YogString*, YogRegexp*, OnigRegion*);
YogKlass* YogRegexp_klass_new(YogEnv*);
YogRegexp* YogRegexp_new(YogEnv*, YogString*, OnigOptionType);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
