#if !defined(__YOG_SET_H__)
#define __YOG_SET_H__

#include "yog/yog.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/set.c */
YOG_EXPORT void YogSet_add(YogEnv*, YogVal, YogVal);
YOG_EXPORT void YogSet_define_classes(YogEnv*, YogVal);
YOG_EXPORT YogVal YogSet_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
