#if !defined(__YOG_SET_H__)
#define __YOG_SET_H__

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
#if defined(__cplusplus)
extern "C" {
#endif
/* src/set.c */
void YogSet_add(YogEnv*, YogVal, YogVal);
YogVal YogSet_define_class(YogEnv*, YogVal);
YogVal YogSet_new(YogEnv*);


#if defined(__cplusplus)
}
#endif
/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
