#if !defined(__YOG_SPRINTF_H__)
#define __YOG_SPRINTF_H__

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/sprintf.c */
YogVal YogSprintf_sprintf(YogEnv*, const char*, ...);
YogVal YogSprintf_vsprintf(YogEnv*, const char*, va_list);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
