#if !defined(YOG_STAT_H_INCLUDED)
#define YOG_STAT_H_INCLUDED

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */
/* src/stat.c */
YOG_EXPORT void YogStat_define_classes(YogEnv*, YogHandle*);
YOG_EXPORT YogVal YogStat_lstat(YogEnv*, YogHandle*);
YOG_EXPORT YogVal YogStat_stat(YogEnv*, YogHandle*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
