#ifndef __YOG_STRING_H__
#define __YOG_STRING_H__

#include "yog/yog.h"

struct YogCharArray {
    unsigned int size;
    unsigned int capacity;
    char items[0];
};

typedef struct YogCharArray YogCharArray;

struct YogString {
    YOGBASICOBJ_HEAD;
    struct YogEncoding* encoding;
    struct YogCharArray* body;
};

typedef struct YogString YogString;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/string.c */
YogCharArray* YogCharArray_new(YogEnv*, unsigned int);
YogCharArray* YogCharArray_new_str(YogEnv*, const char*);
char YogString_at(YogEnv*, YogString*, unsigned int);
void YogString_clear(YogEnv*, YogString*);
YogString* YogString_clone(YogEnv*, YogString*);
char* YogString_dup(YogEnv*, const char*);
ID YogString_intern(YogEnv*, YogString*);
YogKlass* YogString_klass_new(YogEnv*);
YogString* YogString_new(YogEnv*);
YogString* YogString_new_format(YogEnv*, const char*, ...);
YogString* YogString_new_size(YogEnv*, unsigned int);
YogString* YogString_new_str(YogEnv*, const char*);
void YogString_push(YogEnv*, YogString*, char);
unsigned int YogString_size(YogEnv*, YogString*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
