#ifndef __YOG_STRING_H__
#define __YOG_STRING_H__

#include "yog/yog.h"

struct YogCharArray {
    unsigned int size;
    unsigned int capacity;
    char items[0];
};

typedef struct YogCharArray YogCharArray;

struct YogString {
    YOGBASICOBJ_HEAD;
    struct YogVal encoding;
    struct YogVal body;
};

typedef struct YogString YogString;

#include "yog/encoding.h"

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/string.c */
YogVal YogCharArray_new(YogEnv*, unsigned int);
YogVal YogCharArray_new_str(YogEnv*, const char*);
char YogString_at(YogEnv*, YogVal, unsigned int);
void YogString_clear(YogEnv*, YogVal);
YogVal YogString_clone(YogEnv*, YogVal);
char* YogString_dup(YogEnv*, const char*);
ID YogString_intern(YogEnv*, YogVal);
YogVal YogString_klass_new(YogEnv*);
YogVal YogString_new(YogEnv*);
YogVal YogString_new_format(YogEnv*, const char*, ...);
YogVal YogString_new_range(YogEnv*, YogVal, const char*, const char*);
YogVal YogString_new_size(YogEnv*, unsigned int);
YogVal YogString_new_str(YogEnv*, const char*);
void YogString_push(YogEnv*, YogVal, char);
unsigned int YogString_size(YogEnv*, YogVal);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
