#ifndef __TOKEN_H__
#define __TOKEN_H__

#include "yog/yog.h"

struct YogToken {
    unsigned int type;
    union {
        ID id;
        YogVal val;
    } u;
    unsigned int lineno;
};

typedef struct YogToken YogToken;

/* PROTOTYPE_START */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/token.c */
YogVal YogToken_new(YogEnv*);

/* PROTOTYPE_END */

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
