#ifndef __YOG_YOG_H__
#define __YOG_YOG_H__

#include <stdlib.h>

#define BOOL    int
#define FALSE   (0)
#define TRUE    (!FALSE)

struct Heap {
    size_t size;
    unsigned char* base;
    unsigned char* free;
    struct Heap* next;
};

typedef struct Heap Heap;

typedef unsigned int ID;

struct YogVm {
    BOOL need_gc;
    Heap* heap;

    ID next_id;
    struct YogTable* id2name;
    struct YogTable* name2id;
};

typedef struct YogVm YogVm;

struct YogEnv {
    YogVm* vm;
};

#define ENV_VM(env) ((env)->vm)

typedef struct YogEnv YogEnv;

enum YogValType {
    VAL_INT, 
    VAL_FLOAT, 
    VAL_OBJ, 
    VAL_TRUE, 
    VAL_FALSE, 
    VAL_NIL, 
    VAL_SYMBOL, 
    VAL_STRING, 
};

typedef enum YogValType YogValType;

enum YogObjType {
    OBJ_TABLE, 
    OBJ_TABLE_ENTRY, 
    OBJ_TABLE_ENTRY_ARRAY, 
    OBJ_ARRAY, 
    OBJ_VAL_ARRAY, 
    OBJ_NODE, 
};

typedef enum YogObjType YogObjType;

struct YogObj {
    YogObjType type;
    void* forwarding_addr;
    size_t size;
};

#define YOGOBJ_HEAD                 YogObj obj_head
#define YOGOBJ(obj)                 ((YogObj*)(obj))
#define YOGOBJ_FORWARDING_ADDR(obj) (YOGOBJ(obj)->forwarding_addr)
#define YOGOBJ_SIZE(obj)            (YOGOBJ(obj)->size)

typedef struct YogObj YogObj;

struct YogVal {
    YogValType type;
    union {
        int n;
        double f;
        ID symbol;
        YogObj* obj;
        const char* s;
    } u;
};

#define YOGVAL_TYPE(v)      ((v).type)
#define YOGVAL_INT(v)       ((v).u.n)
#define YOGVAL_FLOAT(v)     ((v).u.f)
#define YOGVAL_SYMBOL(v)    ((v).u.symbol)
#define YOGVAL_OBJ(v)       ((v).u.obj)
#define YOGVAL_STRING(v)    ((v).u.s)

typedef struct YogVal YogVal;

struct YogHashType {
    int (*compare)(YogEnv*, YogVal, YogVal);
    int (*hash)(YogEnv*, YogVal);
};

typedef struct YogHashType YogHashType;

struct YogTableEntry {
    YOGOBJ_HEAD;
    unsigned int hash;
    YogVal key;
    YogVal record;
    struct YogTableEntry* next;
};

typedef struct YogTableEntry YogTableEntry;

struct YogTableEntryArray {
    YOGOBJ_HEAD;
    unsigned int size;
    YogTableEntry* items[0];
};

typedef struct YogTableEntryArray YogTableEntryArray;

struct YogTable {
    YOGOBJ_HEAD;
    YogHashType* type;
    int num_bins;
    int num_entries;
    YogTableEntryArray* bins;
};

typedef struct YogTable YogTable;

struct YogValArray {
    YOGOBJ_HEAD;
    unsigned int size;
    YogVal items[0];
};

typedef struct YogValArray YogValArray;

struct YogArray {
    YOGOBJ_HEAD;
    unsigned int size;
    YogValArray* body; 
};

typedef struct YogArray YogArray;

enum YogNodeType {
    NODE_ASSIGN, 
    NODE_ADD, 
    NODE_CALL, 
};

typedef enum YogNodeType YogNodeType;

struct YogNode {
    YOGOBJ_HEAD;
    YogNodeType type;
    union {
        ID id;
        YogVal val;
        struct YogNode* node;
        YogArray* array;
    } u1;
    union {
        struct YogNode* node;
    } u2;
};

#define NODE_LEFT(node)     (node).u1.node
#define NODE_RIGHT(node)    (node).u2.node
#define NODE_ID(node)       (node).u1.id
#define NODE_VAL(node)      (node).u1.val
#define NODE_ARRAY(node)    (node).u1.array

typedef struct YogNode YogNode;

/* $PROTOTYPE_START$ */

/**
 * DON'T EDIT THIS AREA. HERE IS GENERATED BY update_prototype.py.
 */

/* src/array.c */
YogArray* YogArray_new(YogEnv*);

/* src/value.c */
BOOL YogVal_equals_exact(YogEnv*, YogVal, YogVal);
YogVal YogVal_nil();
YogVal YogVal_obj(YogObj*);
YogVal YogVal_int(int);
YogVal YogVal_string(const char*);
YogVal YogVal_symbol(ID);

/* src/parser.y */
void Yog_set_parsing_env(YogEnv*);
YogEnv* Yog_get_parsing_env();

/* src/error.c */
void Yog_assert(YogEnv*, BOOL, const char*);

/* src/st.c */
BOOL YogTable_lookup(YogEnv*, YogTable*, YogVal, YogVal*);
BOOL YogTable_insert(YogEnv*, YogTable*, YogVal, YogVal);
void YogTable_add_direct(YogEnv*, YogTable*, YogVal, YogVal);
YogTable* YogTable_copy(YogEnv*, YogTable*);
BOOL YogTable_delete(YogEnv*, YogTable*, YogVal*, YogVal*);
BOOL YogTable_delete_safe(YogEnv*, YogTable*, YogVal*, YogVal*, YogVal);
BOOL YogTable_foreach(YogEnv*, YogTable*, int (*)(YogEnv*, YogVal, YogVal, YogVal), YogVal);
void YogTable_cleanup_safe(YogEnv*, YogTable*, YogVal);
YogTable* YogTable_new_symbol_table(YogEnv*);
YogTable* YogTable_new_string_table(YogEnv*);

/* src/vm.c */
ID YogVm_intern(YogEnv*, YogVm*, const char*);
YogObj* YogVm_alloc_obj(YogEnv*, YogVm*, YogObjType, size_t);
YogVm* YogVm_new(size_t);

/* $PROTOTYPE_END$ */

#define ALLOC_OBJ(env, obj_type, type)  (type*)YogVm_alloc_obj(env, ENV_VM(env), obj_type, sizeof(type))
#define ALLOC_OBJ_SIZE(env, obj_type, type, size)   (type*)YogVm_alloc_obj(env, ENV_VM(env), obj_type, size)

#endif
/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
 */
