#!/bin/sh

hg="${HOME}/bin/hg"
make="/usr/bin/make"
mkdir="/bin/mkdir"
rm="/bin/rm"

tmpdir="/tmp/$$"
${mkdir} -p "${tmpdir}"

url="http://bitbucket.org/SumiTomohiko/yog"
name="yog"
cd "${tmpdir}"
PYTHONPATH="${HOME}/lib/python" ${hg} clone "${url}" "${name}"
cd "${tmpdir}/${name}"
./configure && ${make}

${rm} -rf "${tmpdir}"

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
