#!/bin/sh

run()
{
  "$@"
  if [ "$?" != 0 ]; then
    echo "Failed: $@"
    exit 1
  fi
}

cleanup()
{
  run rm -rf "${tmp_dir}/${archive}"
}

do_test()
{
  prefix="$(pwd)/$$"
  (cd "${tmp_dir}/${archive}" && run mkdir -p "${prefix}" && run ./configure --prefix="${prefix}" CFLAGS=-I${HOME}/include LDFLAGS=-L${HOME}/lib && run make && run make install && YOG="${prefix}/bin/yog" run make test)
}

archive="${1}"
if [ -z "${archive}" ]; then
  echo "${0} <head>"
  exit 1
fi

tmp_dir="/tmp/$$"
run mkdir -p "${tmp_dir}"
echo "Temporary directory is ${tmp_dir}"

untar="tar xf -"
cwd=`pwd`
echo "Testing ${archive}.tar.xz ..."
cleanup
(cd "${tmp_dir}" && run xzcat "${cwd}/${archive}.tar.xz" | run ${untar})
do_test

run rm -rf "${tmp_dir}"

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
