#!/bin/sh

run()
{
  "$@"
  if [ "$?" != 0 ]; then
    echo "Failed: $@"
    exit 1
  fi
}

cleanup()
{
  run rm -rf "${tmp_dir}/${archive}"
}

do_test()
{
  (cd "${tmp_dir}/${archive}" && run mkdir -p $$ && run ./configure --prefix=`pwd`/$$ CFLAGS=-I${HOME}/include LDFLAGS=-L${HOME}/lib && run make && run make install)
}

archive="${1}"
if [ -z "${archive}" ]; then
  echo "${0} <head>"
  exit 1
fi

tmp_dir="/tmp/$$"
run mkdir -p "${tmp_dir}"
echo "Temporary directory is ${tmp_dir}"

echo "Testing ${archive}.tar.gz ..."
untar="tar xf -"
cwd=`pwd`
(cd "${tmp_dir}" && run zcat "${cwd}/${archive}.tar.gz" | run ${untar})
do_test

echo "Testing ${archive}.tar.bz2 ..."
cleanup
(cd "${tmp_dir}" && run bzcat "${cwd}/${archive}.tar.bz2" | run ${untar})
do_test

which xzcat >/dev/null
if [ $? = 0 ]; then
  echo "Testing ${archive}.tar.xz ..."
  cleanup
  (cd "${tmp_dir}" && run xzcat "${cwd}/${archive}.tar.xz" | run ${untar})
  do_test
fi

echo "Testing ${archive}.zip ..."
cleanup
(cd "${tmp_dir}" && run unzip -q "${cwd}/${archive}.zip")
do_test

run rm -rf "${tmp_dir}"

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
