#!/bin/sh

print_done()
{
  echo "done"
}

python="python"
opts=`getopt --long python: -- "${@}"`
if [ $? != 0 ]; then
  echo "illegal option(s)"
  exit 1
fi
eval set -- "${opts}"
while :
do
  case "${1}" in
  --python)
    python="${2}"
    shift 2
    ;;
  --)
    shift 1
    break
    ;;
  *)
    break
    ;;
  esac
done

yog="src/yog-copying"

archive="${1}"
if [ -z "${archive}" ]; then
  echo "${0} head"
  exit 1
fi

dir="$$"
archive_dir="${dir}/${archive}"

echo -n "Extract source tree..."
mkdir "${dir}"
if [ $? != 0 ]; then
  echo "can't make temporary directory"
  exit 2
fi
git archive "--prefix=${archive_dir}/" HEAD | tar xf -
if [ $? != 0 ]; then
  echo "can't extract source tree"
  exit 2
fi
print_done

echo -n "Generate configure etc..."
(cd "${archive_dir}" && ./autogen.sh)
if [ $? != 0 ]; then
  echo "can't generate configure etc."
  exit 2
fi
rm -rf "${archive_dir}/autom4te.cache"
if [ $? != 0 ]; then
  echo "can't remove autom4te"
  exit 2
fi
srcdir="${archive_dir}/src"
grep -o "\$(MINIYOG) yg2inc.yg [[:alnum:]_]\+.yg \$@" "${srcdir}/Makefile.am" | while read line
do
  yg=`echo "${line}" | cut -d " " -f 2`
  src=`echo "${line}" | cut -d " " -f 3`
  dst="`echo "${src}" | cut -d "." -f 1`.inc"
  ${yog} "${srcdir}/${yg}" "${srcdir}/${src}" "${srcdir}/${dst}"
done
tools_dir=`dirname ${0}`
${yog} "${tools_dir}/make_errno.yg" "${tools_dir}/errno" "${srcdir}/errno.inc"
${python} "${archive_dir}/tools/inst.py" "${srcdir}/insts.def" "${archive_dir}"
if [ $? != 0 ]; then
  echo "can't generate instruction files."
  exit 2
fi
gperf "${srcdir}/keywords" > "${srcdir}/keywords.inc"
print_done

echo -n "Generate HTML document..."
make doc
if [ $? != 0 ]; then
  echo "can't generate document"
  exit 2
fi
cp -r doc/html "${archive_dir}/doc"
if [ $? != 0 ]; then
  echo "can't copy documents"
  exit 2
fi
print_done

echo -n "Archive .tar.gz..."
(cd "${dir}" && tar czf "../${archive}.tar.gz" "${archive}")
if [ $? != 0 ]; then
  echo "can't archive .tar.gz"
  exit 2
fi
print_done
echo -n "Archive .tar.bz2..."
(cd "${dir}" && tar cjf "../${archive}.tar.bz2" "${archive}")
if [ $? != 0 ]; then
  echo "can't archive .tar.bz2"
  exit 2
fi
print_done
echo -n "Archive .tar.xz..."
(cd "${dir}" && tar c "${archive}" | xz --compress > "../${archive}.tar.xz")
if [ $? != 0 ]; then
  echo "can't archive .tar.xz"
  exit 2
fi
print_done
echo -n "Archive .zip..."
(cd "${dir}" && zip -qr "../${archive}.zip" "${archive}")
if [ $? != 0 ]; then
  echo "can't archive .zip"
  exit 2
fi
print_done

rm -rf "${dir}"
if [ $? != 0 ]; then
  echo "can't cleanup temporary directory"
  exit 2
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
