#!/bin/sh

old="${1}"
new="${2}"
if [ -z "${old}" -o -z "${new}" ]; then
  echo "${0} <old version> <new version>"
  exit 1
fi

for f in "README" "configure.ac" "vs/2003/Yog-${old}.wxs" "vs/2003/Makefile" \
         "vs/2003/Yog/config.h"
do
  if [ ! -f "${f}" ]; then
    continue
  fi
  tmp=$$
  sed "s/${old}/${new}/g" < "${f}" > "${tmp}"
  mv "${tmp}" "${f}"
done

for f in "vs/2003/Yog-${old}.wxs"
do
  if [ ! -f "${f}" ]; then
    continue
  fi
  to=`echo "${f}" | sed "s/${old}/${new}/g"`
  git mv "${f}" "${to}"
done

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
