/**
 * This file was generated by "tools/inst.py src/insts.def" automatically.
 * DO NOT TOUCH!!
 */
#include <stdint.h>
#include "yog/opcodes.h"
#include "yog/yog.h"

unsigned int 
Yog_get_inst_size(OpCode op)
{
    unsigned int inst2size[] = {
        sizeof(uint8_t) + sizeof(ID), /* load_special */
        sizeof(uint8_t) + sizeof(uint8_t), /* push_const */
        sizeof(uint8_t) + sizeof(ID) + sizeof(uint8_t), /* call_method */
        sizeof(uint8_t) + sizeof(ID), /* store_pkg */
        sizeof(uint8_t) + sizeof(uint8_t), /* store_local */
        sizeof(uint8_t) + sizeof(ID) + sizeof(uint8_t), /* call_command */
        sizeof(uint8_t), /* make_func */
        sizeof(uint8_t) + sizeof(uint8_t), /* call_func */
        sizeof(uint8_t) + sizeof(ID), /* load_pkg */
        sizeof(uint8_t) + sizeof(uint8_t), /* load_local */
        sizeof(uint8_t) + sizeof(pc_t), /* jump */
        sizeof(uint8_t) + sizeof(pc_t), /* jump_if_false */

    };

    return inst2size[op];
}

/**
 * vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=c
 */
