#define TK_NEWLINE                         1
#define TK_NAME                            2
#define TK_TRY                             3
#define TK_ELSE                            4
#define TK_END                             5
#define TK_FINALLY                         6
#define TK_WHILE                           7
#define TK_BREAK                           8
#define TK_NEXT                            9
#define TK_RETURN                         10
#define TK_IF                             11
#define TK_CLASS                          12
#define TK_NONLOCAL                       13
#define TK_COMMA                          14
#define TK_GREATER                        15
#define TK_ELIF                           16
#define TK_DEF                            17
#define TK_LPAR                           18
#define TK_RPAR                           19
#define TK_DOUBLE_STAR                    20
#define TK_STAR                           21
#define TK_AMPER                          22
#define TK_EQUAL                          23
#define TK_LESS                           24
#define TK_LSHIFT                         25
#define TK_EQUAL_TILDA                    26
#define TK_PLUS                           27
#define TK_LBRACKET                       28
#define TK_RBRACKET                       29
#define TK_DOT                            30
#define TK_NUMBER                         31
#define TK_REGEXP                         32
#define TK_STRING                         33
#define TK_TRUE                           34
#define TK_FALSE                          35
#define TK_LINE                           36
#define TK_DO                             37
#define TK_LBRACE                         38
#define TK_RBRACE                         39
#define TK_EXCEPT                         40
#define TK_AS                             41
