#define TK_NEWLINE                         1
#define TK_TRY                             2
#define TK_ELSE                            3
#define TK_END                             4
#define TK_FINALLY                         5
#define TK_WHILE                           6
#define TK_BREAK                           7
#define TK_NEXT                            8
#define TK_RETURN                          9
#define TK_IF                             10
#define TK_CLASS                          11
#define TK_NAME                           12
#define TK_NONLOCAL                       13
#define TK_IMPORT                         14
#define TK_COMMA                          15
#define TK_DOT                            16
#define TK_GREATER                        17
#define TK_ELIF                           18
#define TK_DEF                            19
#define TK_LPAR                           20
#define TK_RPAR                           21
#define TK_DOUBLE_STAR                    22
#define TK_STAR                           23
#define TK_AMPER                          24
#define TK_EQUAL                          25
#define TK_AND_AND                        26
#define TK_LESS                           27
#define TK_XOR                            28
#define TK_BAR                            29
#define TK_AND                            30
#define TK_LSHIFT                         31
#define TK_RSHIFT                         32
#define TK_EQUAL_TILDA                    33
#define TK_PLUS                           34
#define TK_MINUS                          35
#define TK_DIV                            36
#define TK_DIV_DIV                        37
#define TK_PERCENT                        38
#define TK_TILDA                          39
#define TK_LBRACKET                       40
#define TK_RBRACKET                       41
#define TK_NUMBER                         42
#define TK_REGEXP                         43
#define TK_STRING                         44
#define TK_SYMBOL                         45
#define TK_NIL                            46
#define TK_TRUE                           47
#define TK_FALSE                          48
#define TK_LINE                           49
#define TK_DO                             50
#define TK_LBRACE                         51
#define TK_RBRACE                         52
#define TK_EXCEPT                         53
#define TK_AS                             54
