#define TK_NEWLINE                         1
#define TK_TRY                             2
#define TK_ELSE                            3
#define TK_END                             4
#define TK_FINALLY                         5
#define TK_WHILE                           6
#define TK_BREAK                           7
#define TK_NEXT                            8
#define TK_RETURN                          9
#define TK_IF                             10
#define TK_CLASS                          11
#define TK_NAME                           12
#define TK_MODULE                         13
#define TK_NONLOCAL                       14
#define TK_IMPORT                         15
#define TK_RAISE                          16
#define TK_COMMA                          17
#define TK_DOT                            18
#define TK_GREATER                        19
#define TK_ELIF                           20
#define TK_DEF                            21
#define TK_LPAR                           22
#define TK_RPAR                           23
#define TK_AT                             24
#define TK_STAR_STAR                      25
#define TK_STAR                           26
#define TK_AND                            27
#define TK_EQUAL                          28
#define TK_COLON                          29
#define TK_AND_AND_EQUAL                  30
#define TK_BAR_BAR_EQUAL                  31
#define TK_PLUS_EQUAL                     32
#define TK_MINUS_EQUAL                    33
#define TK_STAR_EQUAL                     34
#define TK_DIV_EQUAL                      35
#define TK_DIV_DIV_EQUAL                  36
#define TK_PERCENT_EQUAL                  37
#define TK_BAR_EQUAL                      38
#define TK_AND_EQUAL                      39
#define TK_XOR_EQUAL                      40
#define TK_STAR_STAR_EQUAL                41
#define TK_LSHIFT_EQUAL                   42
#define TK_RSHIFT_EQUAL                   43
#define TK_BAR_BAR                        44
#define TK_AND_AND                        45
#define TK_NOT                            46
#define TK_EQUAL_EQUAL                    47
#define TK_NOT_EQUAL                      48
#define TK_LESS                           49
#define TK_LESS_EQUAL                     50
#define TK_GREATER_EQUAL                  51
#define TK_XOR                            52
#define TK_BAR                            53
#define TK_LSHIFT                         54
#define TK_RSHIFT                         55
#define TK_EQUAL_TILDA                    56
#define TK_PLUS                           57
#define TK_MINUS                          58
#define TK_DIV                            59
#define TK_DIV_DIV                        60
#define TK_PERCENT                        61
#define TK_TILDA                          62
#define TK_LBRACKET                       63
#define TK_RBRACKET                       64
#define TK_NUMBER                         65
#define TK_REGEXP                         66
#define TK_STRING                         67
#define TK_SYMBOL                         68
#define TK_NIL                            69
#define TK_TRUE                           70
#define TK_FALSE                          71
#define TK_SUPER                          72
#define TK_LINE                           73
#define TK_LBRACE                         74
#define TK_RBRACE                         75
#define TK_EQUAL_GREATER                  76
#define TK_DO                             77
#define TK_EXCEPT                         78
#define TK_AS                             79
